OLED_ENABLE = yes
OLED_DRIVER = SSD1306
LED_BACK_ENABLE = no        # LED backlight (Enable WS2812 RGB underlight.)
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_SUPPORTED = yes
TAP_DANCE_ENABLE = yes

